// Generated by `bun script/migration.ts --name session_fork`. t-uhxos2: a fork's
// source chat and fork point, so a fork reopened later still has its sub-agent
// roster. NULLABLE, no default, no backfill: NULL = not a fork, or a fork made
// before this column (acp/history-store.ts `roster` says what those get). ALTER
// ADD only, so 0.4.172 (which has no such migration or column) reads the store
// as before.
import { Effect } from "effect"
import type { DatabaseMigration } from "../migration"

export default {
  id: "20260924014247_session_fork",
  up(tx) {
    return Effect.gen(function* () {
      yield* tx.run(`ALTER TABLE \`session\` ADD \`fork_session_id\` text;`)
      yield* tx.run(`ALTER TABLE \`session\` ADD \`fork_time\` integer;`)
    })
  },
} satisfies DatabaseMigration.Migration
