// Generated by `bun script/migration.ts --name session_steps`. NULLABLE with no
// default on purpose: NULL = "not counted yet". The count itself is NOT done
// here: it reads every part of the store (3.8-4.9 s on a warm copy of the
// owner's 16 GB store, t-ucn8zm M7), so `SessionSteps.backfill` does it in the
// background after start, one session at a time.
import { Effect } from "effect"
import type { DatabaseMigration } from "../migration"

export default {
  id: "20260923235007_session_steps",
  up(tx) {
    return Effect.gen(function* () {
      yield* tx.run(`ALTER TABLE \`session\` ADD \`steps\` integer;`)
    })
  },
} satisfies DatabaseMigration.Migration
