// Generated by `bun script/migration.ts --name session_request_memory`.
// t-w2qb1x: per-session request memory, so a restarted engine sends the bytes
// the same engine would have sent (engine session/request-memory.ts). A new
// table only: a build without this migration reads the store as before.
import { Effect } from "effect"
import type { DatabaseMigration } from "../migration"

export default {
  id: "20260924222201_session_request_memory",
  up(tx) {
    return Effect.gen(function* () {
      yield* tx.run(`
        CREATE TABLE \`session_request_memory\` (
          \`session_id\` text NOT NULL,
          \`kind\` text NOT NULL,
          \`key\` text NOT NULL,
          \`data\` text NOT NULL,
          CONSTRAINT \`session_request_memory_pk\` PRIMARY KEY(\`session_id\`, \`kind\`, \`key\`),
          CONSTRAINT \`fk_session_request_memory_session_id_session_id_fk\` FOREIGN KEY (\`session_id\`) REFERENCES \`session\`(\`id\`) ON DELETE CASCADE
        );
      `)
    })
  },
} satisfies DatabaseMigration.Migration
