// Generated by `bun script/migration.ts --name add_todo_depth`, then EDITED:
// the generator also emitted `ALTER TABLE collab ADD concurrency` and
// `ADD flavor`, because schema.json (the incremental baseline) had never been
// regenerated after those two migrations were hand-written on 2026-08-18. Both
// columns already exist on every migrated database, so replaying them here
// would fail the whole transaction with a duplicate column. schema.json is
// updated in this change and now records them, so the next generated migration
// starts from the real schema.
import { Effect } from "effect"
import type { DatabaseMigration } from "../migration"

export default {
  id: "20260829173056_add_todo_depth",
  up(tx) {
    return Effect.gen(function* () {
      yield* tx.run(`ALTER TABLE \`todo\` ADD \`depth\` integer DEFAULT 0 NOT NULL;`)
    })
  },
} satisfies DatabaseMigration.Migration
