// Agent Manager - tickets.ts (Folds board): the ticket LAYER. A ticket is a
// markdown file at <repoRoot>/.origami/tickets/<id>.md and the FILE is the only
// truth - humans and agents edit it directly - so every write here is a targeted
// edit of the frontmatter lines this layer owns: unknown keys ride through
// verbatim (a fixed-field rebuild would silently eat a hand-added key, the
// collabAgentDef serializer bug class). The ticket is the entity; the fold is
// provisioned when work starts, so the launch path stamps the ticket's lifecycle
// and a delete before merge hands the ticket back to Todo.
//
// The DOCUMENT format - the frontmatter round-trip, the scalar/list readers and
// the two body sections - lives in ticketDoc.ts, extracted at this file's line
// cap because it is the half that proves itself on strings alone. It is
// re-exported below, so every caller keeps the one import it already had.
//
// Deliberately vscode-free, and it imports run.ts / fanout.ts as TYPES ONLY
// (the launchers arrive through TicketCtx) - so this module unit-tests against a
// real temp dir and no import cycle can form with the run lifecycle, which
// imports stampFold from here.

import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { loadState } from './state';
import { acceptance, appendLog, list, parseTicket, scalar, serializeTicket, setScalar, type Ticket } from './ticketDoc';
import type { Runtime } from './manager';
import type { RunContext } from './run';
import type { Variant } from './fanout';

export { acceptance, list, parseTicket, scalar, serializeTicket, type Ticket } from './ticketDoc';

/** Stored ticket status. `closed` is hidden (no column); `blocked` is DERIVED in
 *  the webview from the fold row (needsYou / error) and is NEVER stored. */
export type TicketStatus = 'triage' | 'todo' | 'pending' | 'in_progress' | 'done' | 'merged' | 'closed';

/** The board's per-ticket wire shape (contract §5). */
export interface TicketRow {
  id: string;
  title: string;
  status: string;
  priority: string;
  labels: string[];
  assignee: string;
  acceptance: { done: number; total: number };
  updatedAt: number;
  fold: string;
  branch: string;
  /** The file is on disk but did not parse (no frontmatter / no id / no title).
   *  It becomes a WARNING row on the board - never silently dropped. */
  malformed?: boolean;
  /** A spec session is LIVE on this ticket (specRun.ts) - the card pulses a
   *  "speccing…" chip. PROCESS state, not a file field: absent again the moment
   *  the session ends, however it ends. */
  spec?: boolean;
}

export function ticketsDir(repoRoot: string): string {
  return path.join(repoRoot, '.origami', 'tickets');
}

export function ticketPath(repoRoot: string, id: string): string {
  return path.join(ticketsDir(repoRoot), `${id}.md`);
}

// ---------------------------------------------------------------------------
// Read / write
// ---------------------------------------------------------------------------

function ticketFiles(repoRoot: string): string[] {
  try {
    return fs.readdirSync(ticketsDir(repoRoot))
      .filter((f) => f.toLowerCase().endsWith('.md'))
      .sort()
      .map((f) => path.join(ticketsDir(repoRoot), f));
  } catch { return []; } // no tickets dir = no tickets
}

export function listTickets(repoRoot: string): Ticket[] {
  const out: Ticket[] = [];
  for (const file of ticketFiles(repoRoot)) {
    try { out.push(parseTicket(fs.readFileSync(file, 'utf8'), file)); } catch { /* unreadable: skip */ }
  }
  return out;
}

export function readTicket(repoRoot: string, id: string): Ticket | undefined {
  // The id comes off a webview message and is pasted straight into a path, so an
  // id carrying separators or `..` would let amTicketOpen open (and a stamp
  // rewrite) any file on disk. Ids are generated by newTicketId: hold them to it.
  if (!/^[A-Za-z0-9._-]+$/.test(id)) return undefined;
  const file = ticketPath(repoRoot, id);
  try { return parseTicket(fs.readFileSync(file, 'utf8'), file); } catch { return undefined; }
}

/** Atomic write (tmp + rename), mirroring state.ts saveState - a crash mid-write
 *  can't half-eat a ticket the user is also editing. */
function writeTicket(t: Ticket): void {
  fs.mkdirSync(path.dirname(t.file), { recursive: true });
  const tmp = `${t.file}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, serializeTicket(t));
  fs.renameSync(tmp, t.file);
}

// ---------------------------------------------------------------------------
// Board projection
// ---------------------------------------------------------------------------

export function ticketRow(t: Ticket, spec = false): TicketRow {
  const updated = Date.parse(scalar(t.fm, 'updated'));
  let mtime = 0;
  try { mtime = fs.statSync(t.file).mtimeMs; } catch { /* vanished mid-read */ }
  return {
    id: t.id,
    title: scalar(t.fm, 'title') || t.id,
    status: scalar(t.fm, 'status') || 'triage',
    priority: scalar(t.fm, 'priority') || 'normal',
    labels: list(t.fm, 'labels'),
    assignee: scalar(t.fm, 'assignee'),
    acceptance: acceptance(t.body),
    updatedAt: Number.isNaN(updated) ? mtime : updated,
    fold: scalar(t.fm, 'fold'),
    branch: scalar(t.fm, 'branch'),
    ...(t.malformed ? { malformed: true } : {}),
    ...(spec ? { spec: true } : {}),
  };
}

/** Every ticket of a repo, board-shaped. `closed` rides along - the webview
 *  hides it (v1 has no Closed column); the count still tells the truth. `isSpec`
 *  is passed IN: specRun.ts owns the marks and needs this module, so importing
 *  it back here would close a cycle. */
export function boardTickets(repoRoot: string, isSpec?: (id: string) => boolean): TicketRow[] {
  return listTickets(repoRoot).map((t) => ticketRow(t, isSpec?.(t.id) === true));
}

/** id -> title for the repo's tickets, so buildRows can label a fold row with the
 *  ticket it came from and stay pure (it never reads the tickets dir itself). */
export function ticketTitles(repoRoot: string): Map<string, string> {
  return new Map(listTickets(repoRoot).map((t) => [t.id, scalar(t.fm, 'title') || t.id]));
}

// ---------------------------------------------------------------------------
// Ids + naming
// ---------------------------------------------------------------------------

/** `t-` + 6 base36 chars: 4 time-derived (so ids sort roughly by age) + 2 random. */
export function newTicketId(now = Date.now()): string {
  const time = now.toString(36).slice(-4);
  const rand = Math.random().toString(36).slice(2, 4).padEnd(2, '0');
  return `t-${time}${rand}`;
}

/** A title as a branch/dir-safe slug (the worktree sanitizer's alphabet). */
export function slug(title: string): string {
  return (title || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

/** The worktree/branch name a launch uses. The id goes FIRST: sanitizeWorktreeName
 *  caps the result at 40 chars, so a long title loses its tail rather than the id
 *  that links the fold back to its ticket. */
export function launchName(id: string, title: string): string {
  return `${id}-${slug(title).slice(0, 28)}`;
}

/** The prompt a launched fold is driven with: the title, WHICH REPO the ticket
 *  belongs to, the body verbatim (objective, constraints AND the acceptance
 *  checklist), then the one instruction the agent needs to close the loop back
 *  onto the file. The repo line exists because a fold session's cwd is a
 *  worktree named after the TICKET - without it the agent has to infer which
 *  board its board_update lands on. Omitted when the caller has no name to give,
 *  so the line is never a confident guess. */
export function launchPrompt(t: Ticket, repoName = ''): string {
  const title = scalar(t.fm, 'title') || t.id;
  const body = t.body.trim();
  return [
    title,
    repoName ? `This ticket is on the "${repoName}" Folds board.` : '',
    body,
    `When the work is done, tick the acceptance boxes on ticket ${t.id} via a board_update comment.`,
  ].filter((s) => s.length > 0).join('\n\n');
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Write status/fold/branch/updated + an optional log line. Refuses a malformed
 *  file outright (rewriting one would destroy whatever the human meant). */
function mutate(t: Ticket, fields: Record<string, string>, note: string | undefined, now: number): void {
  if (t.malformed) return;
  for (const [k, v] of Object.entries(fields)) setScalar(t, k, v);
  setScalar(t, 'updated', new Date(now).toISOString());
  if (note) t.body = appendLog(t.body, note, now);
  writeTicket(t);
}

/** Quick-add: a raw idea lands in Triage. The optional `body` is the form's
 *  tasks field, written as the ticket body verbatim; an empty one leaves the file
 *  byte-identical to a title-only quick-add. `acceptance` items land the ticket in
 *  Todo instead (matching board_create). Returns the new id ('' on failure). */
export function quickAdd(repoRoot: string, title: string, body = '', options: { priority?: string; labels?: string[]; acceptance?: string[] } = {}, now = Date.now()): string {
  const { priority = 'normal', labels = [], acceptance = [] } = options;
  const status = acceptance.length ? 'todo' : 'triage';
  const id = newTicketId(now);
  const iso = new Date(now).toISOString();
  const file = ticketPath(repoRoot, id);
  const prose = body.trim() ? `\n${body.trim()}\n` : '';
  const labelsLine = labels.length ? `\nlabels: [${labels.join(', ')}]` : '';
  const acceptanceSection = acceptance.length ? `\n\n## Acceptance\n\n${acceptance.map((a) => `- [ ] ${a}`).join('\n')}` : '';
  const text = `---\nid: ${id}\ntitle: ${title}\nstatus: ${status}\npriority: ${priority}${labelsLine}\ncreated: ${iso}\nupdated: ${iso}\n---\n${prose}${acceptanceSection}\n## Log\n\n- ${iso} folds: created via quick-add\n`;
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
    return id;
  } catch { return ''; }
}

/** Append a Log line, optionally moving the status with it - the spec flow's one
 *  write (specRun.ts): "spec complete" carries the ticket to Todo, "ended without
 *  acceptance" records the attempt and leaves the status where it was. */
export function noteTicket(repoRoot: string, id: string, note: string, status?: TicketStatus, now = Date.now()): void {
  const t = readTicket(repoRoot, id);
  if (t) mutate(t, status ? { status } : {}, note, now);
}

/** Hide a ticket (v1 has no Closed column). Never deletes the file. */
export function closeTicket(repoRoot: string, id: string, now = Date.now()): void {
  const t = readTicket(repoRoot, id);
  if (t) mutate(t, { status: 'closed' }, 'closed from the board', now);
}

/** Stamp the ticket a FOLD RECORD is linked to. The record is the source of the
 *  link (rec.ticketId) and of the fold/branch values, so every lifecycle call
 *  site is one line and nothing has to thread the ticket id through the run
 *  lifecycle. A record with no ticket is a no-op (a plain, ticket-less fold). */
export function stampFold(repoRoot: string, recId: string, status: TicketStatus, note?: string, now = Date.now()): void {
  const rec = loadState(repoRoot).worktrees.find((r) => r.id === recId);
  if (!rec?.ticketId) return;
  const t = readTicket(repoRoot, rec.ticketId);
  if (t) mutate(t, { status, fold: rec.id, branch: rec.branch }, note, now);
}

/** Hand a ticket back to Todo and drop its fold link - the fold was deleted (or
 *  its create was cancelled) BEFORE it merged, so the work still has to happen. */
export function unlinkTicket(repoRoot: string, ticketId: string, note: string, now = Date.now()): void {
  const t = readTicket(repoRoot, ticketId);
  if (t) mutate(t, { status: 'todo', fold: '', branch: '' }, note, now);
}

// ---------------------------------------------------------------------------
// Change detection (the 5s poll) + live activity
// ---------------------------------------------------------------------------

/** Per-process debounce caches for the poll and the activity broadcast. They live
 *  here rather than on AgentManager so the fleet owner holds no ticket state (and
 *  stays under its line cap). resetTicketWatch() clears both, for tests. */
const dirHashes = new Map<string, string>();
let activityGate = 0;
const ACTIVITY_THROTTLE_MS = 2000;

function watchKey(repoRoot: string): string {
  return process.platform === 'win32' ? path.resolve(repoRoot).toLowerCase() : path.resolve(repoRoot);
}

/** A content hash of the tickets dir. Content, not mtime: an agent or a human can
 *  rewrite a ticket within one clock tick at the same size, and the board has to
 *  see it. Dirs are small (tens of short files), so this is cheap at 5s. */
export function ticketsHash(repoRoot: string): string {
  const h = crypto.createHash('sha1');
  for (const file of ticketFiles(repoRoot)) {
    h.update(path.basename(file));
    h.update('\0');
    try { h.update(fs.readFileSync(file)); } catch { /* vanished mid-scan */ }
    h.update('\0');
  }
  return h.digest('hex');
}

/** True when this repo's tickets dir changed since the last check (first check
 *  on a repo counts as changed, so the board paints its tickets at boot). */
export function ticketsChanged(repoRoot: string): boolean {
  const key = watchKey(repoRoot);
  const hash = ticketsHash(repoRoot);
  if (dirHashes.get(key) === hash) return false;
  dirHashes.set(key, hash);
  return true;
}

export function resetTicketWatch(): void {
  dirHashes.clear();
  activityGate = 0;
}

/** One line of "what this fold is doing now", clamped to 120 chars. A tool title
 *  is clamped at the HEAD (the verb is the useful half); a thought is clamped at
 *  the TAIL (the newest words are). Whitespace is collapsed - a raw ACP chunk is
 *  multi-line and would break the card's one-line row. */
export function activityLine(raw: string, keep: 'head' | 'tail' = 'head'): string {
  const flat = (raw || '').replace(/\s+/g, ' ').trim();
  if (flat.length <= 120) return flat;
  return keep === 'tail' ? `…${flat.slice(-119)}` : `${flat.slice(0, 119)}…`;
}

/** Stamp a fold's activity from an ACP event, keyed by the LIVE session it runs
 *  on (the reverse of runtime.sessionId - setAgentQuestion's lookup). A session
 *  the manager does not own (the user's own chat) is a no-op. The value is ALWAYS
 *  stored; only the BROADCAST is throttled to a >=2s leading edge, so a chatty
 *  tool stream can't flood the board and the next tick still carries the latest.
 *  Returns true when the caller should broadcast. */
export function stampActivity(runtime: Map<string, Runtime>, sessionId: string, raw: string, now = Date.now()): boolean {
  const text = activityLine(raw);
  if (!sessionId || !text) return false;
  let id: string | undefined;
  for (const [rid, rt] of runtime) if (rt.sessionId === sessionId) { id = rid; break; }
  if (id === undefined) return false;
  const rt = runtime.get(id);
  if (!rt || rt.activity === text) return false;
  runtime.set(id, { ...rt, activity: text });
  if (now - activityGate < ACTIVITY_THROTTLE_MS) return false;
  activityGate = now;
  return true;
}

// ---------------------------------------------------------------------------
// Message routing (amTicket*)
// ---------------------------------------------------------------------------

/** The window the ticket routing drives the fleet owner through. The two
 *  launchers arrive as VALUES (runCreate / runFanout) so this module needs no
 *  runtime import of the run lifecycle - which imports stampFold from here. */
export interface TicketCtx {
  run: RunContext;
  validateRoot(raw: unknown): string | undefined;
  broadcast(): void;
  create(ctx: RunContext, root: string, rawName: string, agentName: string, prompt: string, model: string, start: boolean): Promise<void>;
  fanout(ctx: RunContext, root: string, rawName: string, prompt: string, variants: Variant[], start: boolean): Promise<void>;
  /** The spec conversation (specRun.runSpec), a VALUE for the same reason the two launchers are: it imports this module. */
  spec(ctx: RunContext, root: string, id: string, agentName: string, model: string): Promise<void>;
  /** The BOARD name of the entry a message named — what the engine's board_*
   *  tools resolve. Optional: absent falls back to the primary's basename. */
  repoName?(raw: unknown): string;
}

/** Provision a fold for a ticket. The ticket id rides the RunContext, so a
 *  single create AND every race sibling link back to it without fanout.ts
 *  needing to know tickets exist; runCreate stamps pending/in_progress from the
 *  record it just wrote. */
async function launch(ctx: TicketCtx, root: string, m: { [k: string]: unknown }): Promise<void> {
  const amError = (message: string) => ctx.run.host.post({ type: 'amError', message });
  const t = readTicket(root, String(m.id ?? ''));
  if (!t) { amError('That ticket no longer exists.'); return; }
  if (t.malformed) { amError(`Ticket ${t.id} does not parse — fix its frontmatter before launching it.`); return; }
  if (scalar(t.fm, 'fold')) { amError(`Ticket ${t.id} already has a fold.`); return; }
  const run: RunContext = { ...ctx.run, ticketId: t.id };
  const rawName = launchName(t.id, scalar(t.fm, 'title'));
  // The prompt names the ENTRY's board name — the engine's board_* tools
  // resolve that, not a path. `root` is the primary checkout, whose basename
  // can differ from the board name (Origami Coder: primary v2-rebase, board
  // name origami-coder), so it is only the fallback.
  const prompt = launchPrompt(t, ctx.repoName?.(m.root) || path.basename(root));
  const start = m.start !== false;
  if (Array.isArray(m.variants) && m.variants.length > 0) {
    const variants = (m.variants as Array<Record<string, unknown>>).map((v) => ({ agentName: String(v.agentName ?? ''), model: String(v.model ?? '') }));
    await ctx.fanout(run, root, rawName, prompt, variants, start);
  } else {
    await ctx.create(run, root, rawName, String(m.agentName ?? ''), prompt, String(m.model ?? ''), start);
  }
}

/** Route an `amTicket*` message. Root validation is the board's standard scoped
 *  check (amError + stop), exactly like every other repo-scoped action. */
export async function handleTicketMessage(ctx: TicketCtx, m: { type?: string; [k: string]: unknown }): Promise<void> {
  const root = ctx.validateRoot(m.root);
  if (!root) return; // validateRoot already surfaced amError
  switch (m.type) {
    case 'amTicketQuickAdd': {
      const title = String(m.title ?? '').trim();
      if (!title) { ctx.run.host.post({ type: 'amError', message: 'A ticket needs a title.' }); return; }
      const priority = m.priority !== undefined ? String(m.priority) : undefined;
      const labels = Array.isArray(m.labels) ? (m.labels as unknown[]).map(String).filter(Boolean) : undefined;
      const acceptance = Array.isArray(m.acceptance) ? (m.acceptance as unknown[]).map(String).filter(Boolean) : undefined;
      quickAdd(root, title, String(m.body ?? ''), { priority, labels, acceptance });
      ctx.broadcast();
      return;
    }
    case 'amTicketOpen': {
      // The full-brief editor IS the file - open it rather than mirror it in a form.
      const t = readTicket(root, String(m.id ?? ''));
      if (t) ctx.run.host.openFile(t.file);
      else ctx.run.host.post({ type: 'amError', message: 'That ticket no longer exists.' });
      return;
    }
    case 'amTicketClose': {
      closeTicket(root, String(m.id ?? ''));
      ctx.broadcast();
      return;
    }
    case 'amTicketLaunch': {
      await launch(ctx, root, m);
      return;
    }
    case 'amTicketSpec': {
      // No fold, no worktree: it runs at the repo root and edits the ticket file itself.
      await ctx.spec(ctx.run, root, String(m.id ?? ''), String(m.agentName ?? ''), String(m.model ?? ''));
      return;
    }
  }
}
