// cronMac — the macOS cron surface: the sh launcher, the plist, the launchctl
// argv, and the platform forks in the shared helpers. Everything here passes
// `'darwin'` (or a fake run/temp dir) EXPLICITLY, so the suite asserts the Mac
// artifacts identically on any OS — the mirror of the win32 pin the Windows
// cron suites carry. What no unit test can see: the real launchctl's
// behaviour. That is exercised on the Mac itself, not asserted here.

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { cronScriptRelPath, taskNameFor, LAUNCHD_LABEL_PREFIX, type RunCommandSpec } from '../../../src/dashboard/crons/cronCommand';
import { buildLauncherScript, taskCommand, trLengthError } from '../../../src/dashboard/crons/cronLauncher';
import { buildLauncherScriptPosix, launchdScheduleXml, parseLaunchctlList, plistFor, runInvocationPosix, shQuote } from '../../../src/dashboard/crons/cronPosix';
import { launchdBackend, type LaunchctlRun } from '../../../src/dashboard/crons/launchdBackend';

const BIN = '/Users/user/.origami/bin/origami';
const WS = '/Users/user/Desktop/my project';
const LOG = '/Users/user/Desktop/my project/.origami/cron-logs/c123.log';
const base: RunCommandSpec = { binary: BIN, name: 'nightly triage', prompt: 'triage the board', workspace: WS, logPath: LOG };

describe('cronMac — platform forks in the shared helpers', () => {
  it('taskNameFor is a launchd label on darwin, a Task Scheduler path on win32', () => {
    expect(taskNameFor('c123', 'darwin')).toBe('com.origami.cron.c123');
    expect(taskNameFor('c123', 'win32')).toBe('\\Origami\\c123');
  });

  it('the launcher is <id>.sh on darwin, <id>.cmd on win32', () => {
    expect(cronScriptRelPath('c123', 'darwin')).toBe(path.join('.origami', 'crons', 'c123.sh'));
    expect(cronScriptRelPath('c123', 'win32')).toBe(path.join('.origami', 'crons', 'c123.cmd'));
  });

  it('taskCommand is the BARE script path on darwin (launchd takes an argv, quoting would join the filename)', () => {
    expect(taskCommand('/a/b c/x.sh', 'darwin')).toBe('/a/b c/x.sh');
    expect(taskCommand('C:\\a\\x.cmd', 'win32')).toBe('"C:\\a\\x.cmd"');
  });

  it('the /TR length cap is schtasks-only — darwin never refuses on path length', () => {
    const deep = '/Users/user/' + 'very-deep/'.repeat(40) + 'ws/.origami/crons/c1.sh';
    expect(trLengthError(deep, 'darwin')).toBeNull();
    expect(trLengthError(deep.replace(/\//g, '\\'), 'win32')).toMatch(/nested too deeply/);
  });

  it('buildLauncherScript(darwin) delegates to the posix builder', () => {
    expect(buildLauncherScript(base, 'darwin')).toBe(buildLauncherScriptPosix(base));
  });
});

describe('cronMac — shQuote + the posix invocation', () => {
  it('single-quotes tokens; only the quote itself needs an escape', () => {
    expect(shQuote('plain')).toBe(`'plain'`);
    expect(shQuote(`don't`)).toBe(`'don'\\''t'`);
    // $ and backticks are LITERAL inside single quotes — no escaping, no expansion.
    expect(shQuote('summarise $HOME `ls`')).toBe(`'summarise $HOME \`ls\`'`);
  });

  it('the invocation carries binary/prompt/--auto/--dir (+ agent/model when set), sh-quoted', () => {
    expect(runInvocationPosix(base)).toBe(
      `'${BIN}' run 'triage the board' --auto --dir '${WS}'`,
    );
    expect(runInvocationPosix({ ...base, agent: 'build', model: 'p/m' })).toContain(`--agent 'build' --model 'p/m'`);
  });
});

describe('cronMac — the sh launcher script', () => {
  const lines = buildLauncherScriptPosix(base).split('\n');

  it('starts with the shebang and the do-not-edit notice', () => {
    expect(lines[0]).toBe('#!/bin/sh');
    expect(lines[1]).toContain('Generated by Origami Crons');
  });

  it('[start] comes before the run, so a killed run leaves a start with no end', () => {
    const start = lines.findIndex((l) => l.includes('[start]'));
    const run = lines.findIndex((l) => l.startsWith(`'${BIN}'`));
    const end = lines.findIndex((l) => l.includes('[end]'));
    expect(start).toBeGreaterThan(-1);
    expect(start).toBeLessThan(run);
    expect(run).toBeLessThan(end);
  });

  it('the [cmd] audit line carries the run line byte-identically', () => {
    const line = runInvocationPosix(base);
    expect(lines).toContain(`echo ${shQuote(`[cmd] ${line}`)} >> "$LOG"`);
    expect(lines).toContain(`${line} >> "$LOG" 2>&1`);
  });

  it('captures rc on its OWN line before [end] — $? after $(date) would report date, not the run', () => {
    const rc = lines.indexOf('rc=$?');
    const end = lines.findIndex((l) => l.includes('[end]'));
    expect(rc).toBeGreaterThan(-1);
    expect(rc).toBe(end - 1);
    expect(lines[end]).toContain('exit=$rc');
  });
});

describe('cronMac — schedule → launchd plist', () => {
  it('daily → one StartCalendarInterval dict', () => {
    const xml = launchdScheduleXml({ kind: 'daily', time: '09:30' });
    expect(xml).toContain('StartCalendarInterval');
    expect(xml).toContain('<key>Hour</key><integer>9</integer>');
    expect(xml).toContain('<key>Minute</key><integer>30</integer>');
    expect(xml).not.toContain('Weekday');
  });

  it('weekly → an array of dicts with launchd weekday numbers (Sunday = 0)', () => {
    const xml = launchdScheduleXml({ kind: 'weekly', days: ['MON', 'SUN'], time: '07:05' });
    expect(xml).toContain('<key>Weekday</key><integer>1</integer>');
    expect(xml).toContain('<key>Weekday</key><integer>0</integer>');
    expect(xml).toContain('<key>Minute</key><integer>5</integer>');
  });

  it('hourly/minutely → StartInterval seconds (the registered-at anchor nextRun models)', () => {
    expect(launchdScheduleXml({ kind: 'hourly', every: 6 })).toContain('<key>StartInterval</key><integer>21600</integer>');
    expect(launchdScheduleXml({ kind: 'minutely', every: 15 })).toContain('<key>StartInterval</key><integer>900</integer>');
  });

  it('the plist runs /bin/sh <script> and XML-escapes the path', () => {
    const p = plistFor('com.origami.cron.c1', '/a/b&c/x.sh', { kind: 'daily', time: '09:30' });
    expect(p).toContain('<string>/bin/sh</string>');
    expect(p).toContain('<string>/a/b&amp;c/x.sh</string>');
    expect(p).toContain('<key>Label</key><string>com.origami.cron.c1</string>');
  });
});

describe('cronMac — launchctl list parse', () => {
  it('keeps only labels with our prefix, dropping PID/status columns and foreign agents', () => {
    const out = [
      'PID\tStatus\tLabel',
      '312\t0\tcom.apple.Finder',
      '-\t0\tcom.origami.cron.c1',
      '-\t78\tcom.origami.cron.c2',
      '99\t0\tcom.docker.helper',
      '',
    ].join('\n');
    expect(parseLaunchctlList(out)).toEqual(['com.origami.cron.c1', 'com.origami.cron.c2']);
  });
});

describe('cronMac — launchdBackend against a fake launchctl + temp plist dir', () => {
  function fake(fail?: string, listOut = '') {
    const calls: string[][] = [];
    const run: LaunchctlRun = async (args) => {
      calls.push(args);
      if (fail && args[0] === fail) return { ok: false, error: `${fail} failed` };
      if (args[0] === 'bootout') return { ok: false, error: 'Boot-out failed: 3: No such process' };
      return { ok: true, stdout: args[0] === 'list' ? listOut : '' };
    };
    return { calls, run };
  }
  const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'origami-launchd-'));
  const schedule = { kind: 'daily' as const, time: '09:30' };
  const label = `${LAUNCHD_LABEL_PREFIX}c1`;

  it('register writes the plist, boots the old job out, bootstraps the file', async () => {
    const dir = tmp();
    const { calls, run } = fake();
    const res = await launchdBackend(run, dir, 501).register({ taskName: label, schedule, command: '/ws/.origami/crons/c1.sh' });
    expect(res).toEqual({ ok: true });
    const file = path.join(dir, `${label}.plist`);
    expect(fs.readFileSync(file, 'utf8')).toContain('<string>/ws/.origami/crons/c1.sh</string>');
    expect(calls).toContainEqual(['bootout', `gui/501/${label}`]);
    expect(calls).toContainEqual(['bootstrap', 'gui/501', file]);
  });

  it('a failed bootstrap deletes the plist again — never a half-registration', async () => {
    const dir = tmp();
    const { run } = fake('bootstrap');
    const res = await launchdBackend(run, dir, 501).register({ taskName: label, schedule, command: '/x.sh' });
    expect(res.ok).toBe(false);
    expect(fs.existsSync(path.join(dir, `${label}.plist`))).toBe(false);
  });

  it('unregister treats "No such process" as done and removes the plist', async () => {
    const dir = tmp();
    fs.writeFileSync(path.join(dir, `${label}.plist`), 'x');
    const { run } = fake();
    expect(await launchdBackend(run, dir, 501).unregister(label)).toEqual({ ok: true });
    expect(fs.existsSync(path.join(dir, `${label}.plist`))).toBe(false);
  });

  it('runNow kickstarts the job in the gui domain', async () => {
    const { calls, run } = fake();
    await launchdBackend(run, tmp(), 501).runNow(label);
    expect(calls).toContainEqual(['kickstart', `gui/501/${label}`]);
  });

  it('query lists the domain once and filters to our labels', async () => {
    const { run } = fake(undefined, `-\t0\t${label}\n1\t0\tcom.apple.Dock\n`);
    expect(await launchdBackend(run, tmp(), 501).query()).toEqual({ ok: true, taskNames: [label] });
  });

  it('a genuinely failed query says so rather than reading as "no crons"', async () => {
    const { run } = fake('list');
    const res = await launchdBackend(run, tmp(), 501).query();
    expect(res.ok).toBe(false);
  });
});
