// cronLauncher — the launcher script and the tiny /TR that points at it.
//
// THE TEST THAT MATTERS MOST is the /TR length one. The first version of this
// feature built a ~1500-character self-auditing command line, asserted it
// verbatim, and executed it successfully through cmd — and was still DEAD ON
// ARRIVAL, because `schtasks` refuses any /TR over 261 characters:
//     ERROR: Value for '/TR' option cannot be more than 261 character(s).
// No unit test can see a limit that lives inside schtasks, so the limit is
// encoded here explicitly and checked against a realistically-deep workspace.

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as path from 'node:path';
import { buildLauncherScript, taskCommand, trLengthError, TR_MAX_LENGTH } from '../../../src/dashboard/crons/cronLauncher';
import { cronScriptPath, runInvocation } from '../../../src/dashboard/crons/cronCommand';

// This suite asserts the WINDOWS launcher (batch rules, /TR cap) through the
// helpers' platform DEFAULTS — pin the platform so the same assertions hold
// when the suite runs on macOS. cronMac.test.ts covers the darwin forms.
const realPlatform = Object.getOwnPropertyDescriptor(process, 'platform')!;
beforeAll(() => { Object.defineProperty(process, 'platform', { value: 'win32' }); });
afterAll(() => { Object.defineProperty(process, 'platform', realPlatform); });

const BIN = 'C:\\Users\\dev\\.origami\\bin\\origami.exe';
const WS = 'C:\\Users\\dev\\Desktop\\my project';
const LOG = 'C:\\Users\\dev\\Desktop\\my project\\.origami\\cron-logs\\c123.log';
const base = { binary: BIN, name: 'nightly triage', workspace: WS, logPath: LOG };
const lines = (spec: Parameters<typeof buildLauncherScript>[0]) => buildLauncherScript(spec).split('\r\n');

describe('cronLauncher — /TR fits inside the schtasks limit', () => {
  it('the limit is the real one schtasks enforces', () => {
    expect(TR_MAX_LENGTH).toBe(261);
  });

  it('a realistically-deep workspace still registers — the regression that killed v1', () => {
    // A genuinely long but ordinary Windows path: a nested repo under Desktop.
    const deep = 'C:\\Users\\dev\\Desktop\\origami-coder.wt\\v2-rebase\\packages\\vscode\\some\\nested\\workspace';
    const tr = taskCommand(cronScriptPath(deep, 'cms6lvf8yyt13'));
    expect(tr.length).toBeLessThanOrEqual(TR_MAX_LENGTH);
    expect(trLengthError(cronScriptPath(deep, 'cms6lvf8yyt13'))).toBeNull();
  });

  it('a LONG prompt does not affect /TR at all — the whole reason for a launcher', () => {
    // Under the old inline design this alone blew the limit. Now the prompt
    // lives in the script and /TR is just a path.
    const tr = taskCommand(cronScriptPath(WS, 'c123'));
    expect(tr.length).toBeLessThan(120);
    expect(buildLauncherScript({ ...base, prompt: 'x'.repeat(4000) }).length).toBeGreaterThan(4000);
  });

  it('a workspace nested TOO deeply is refused with a clear reason, not registered broken', () => {
    const absurd = 'C:\\' + Array.from({ length: 20 }, (_, i) => `deeply-nested-directory-number-${i}`).join('\\');
    const script = cronScriptPath(absurd, 'c123');
    const err = trLengthError(script);
    expect(err).not.toBeNull();
    expect(err).toContain('261');
    expect(err).toMatch(/too deeply|closer to the drive root/);
  });

  it('/TR is the quoted script path and nothing else', () => {
    expect(taskCommand('C:\\ws\\.origami\\crons\\c1.cmd')).toBe('"C:\\ws\\.origami\\crons\\c1.cmd"');
  });

  it('the script directory is kept short, because its length is charged to /TR', () => {
    expect(cronScriptPath('C:\\ws', 'c1')).toBe(path.join('C:\\ws', '.origami', 'crons', 'c1.cmd'));
  });
});

describe('cronLauncher — the script body', () => {
  it('is exactly the audit-bracketed form, verbatim', () => {
    expect(buildLauncherScript({ ...base, prompt: 'triage the backlog' })).toBe(
      [
        '@echo off',
        'rem Generated by Origami Crons. Edit the cron in the Crons view, not here —',
        'rem this file is rewritten whenever the cron is saved, and deleted with it.',
        `echo [start] nightly triage %DATE% %TIME% >> "${LOG}" 2>&1`,
        `echo [cmd] "${BIN}" run "triage the backlog" --auto --dir "${WS}" >> "${LOG}"`,
        `"${BIN}" run "triage the backlog" --auto --dir "${WS}" >> "${LOG}" 2>&1`,
        `echo [end] %DATE% %TIME% exit=%ERRORLEVEL% >> "${LOG}"`,
        '',
      ].join('\r\n'),
    );
  });

  it('the [cmd] line BYTE-MATCHES the line that actually runs', () => {
    for (const prompt of ['plain', 'a & b | c > d', 'say "hi" & wait', 'check (a)', '20% faster']) {
      const l = lines({ ...base, prompt });
      const echoed = l[4].slice('echo [cmd] '.length, l[4].lastIndexOf(' >> '));
      const ran = l[5].slice(0, l[5].lastIndexOf(' >> '));
      expect(echoed).toBe(ran);
    }
  });

  it('puts a SPACE before >> on the exit line — `%ERRORLEVEL%>>` parses as a handle-0 redirect', () => {
    // Written closed up, `exit=0>> "log"` redirects handle 0 and the line
    // silently vanishes: the audit trail loses its outcome. Verified by running
    // both forms; only the spaced one produced an [end] record.
    const exitLine = lines({ ...base, prompt: 'go' })[6];
    expect(exitLine).toContain('exit=%ERRORLEVEL% >> ');
    expect(exitLine).not.toContain('%ERRORLEVEL%>>');
  });

  it('uses plain %ERRORLEVEL% — the command-line `call echo %^ERRORLEVEL%` form is wrong in a script', () => {
    const script = buildLauncherScript({ ...base, prompt: 'go' });
    expect(script).not.toContain('%^ERRORLEVEL%');
  });

  it('does NOT prefix the run with `call` — it would add a second percent-expansion pass', () => {
    // With `call`, a prompt reading "summarise %USERPROFILE% please" arrived as
    // "summarise C:\Users\dev please": the %% doubling gets undone.
    const l = lines({ ...base, prompt: 'go' });
    expect(l[5].startsWith('call ')).toBe(false);
    expect(l[5].startsWith(`"${BIN}"`)).toBe(true);
  });

  it('writes [start] BEFORE the run, so a killed job still leaves evidence', () => {
    const l = lines({ ...base, prompt: 'go' });
    expect(l[3]).toContain('[start]');
    expect(l[5]).toContain('run "go"');
    expect(l[6]).toContain('[end]');
  });

  it('carries --auto, because nobody is there to answer a permission ask', () => {
    expect(buildLauncherScript({ ...base, prompt: 'go' })).toContain('--auto');
  });
});

describe('cronLauncher — percent handling (the batch rule that REVERSES the command-line one)', () => {
  it('doubles % so it reaches origami literally', () => {
    // In a batch file `%%` yields one literal `%`; on a command line `%%` would
    // print as `%%`. Same characters, opposite meaning.
    const l = lines({ ...base, prompt: 'make it 20% faster' });
    expect(l[5]).toContain('run "make it 20%% faster"');
  });

  it('a %VAR% in the prompt is doubled, so the environment is NOT substituted', () => {
    const l = lines({ ...base, prompt: 'summarise %USERPROFILE% please' });
    expect(l[5]).toContain('run "summarise %%USERPROFILE%% please"');
  });

  it('leaves OUR OWN %DATE%/%TIME%/%ERRORLEVEL% single, so they DO expand', () => {
    const l = lines({ ...base, prompt: 'go' });
    expect(l[3]).toContain('%DATE% %TIME%');
    expect(l[3]).not.toContain('%%DATE%%');
    expect(l[6]).toContain('exit=%ERRORLEVEL%');
  });

  it('escapes operators in the NAME (bare text) but not inside quoted tokens', () => {
    const l = lines({ ...base, name: 'build & deploy (100%)', prompt: 'a & b' });
    expect(l[3]).toContain('echo [start] build ^& deploy ^(100%%^)');
    // Inside quotes ^ is literal, so escaping there would log a command that
    // differs from the one that ran.
    expect(l[5]).toContain('run "a & b"');
    expect(l[5]).not.toContain('^&');
  });

  it('the invocation itself is unchanged by the launcher wrapping', () => {
    expect(runInvocation({ ...base, prompt: 'go', model: 'vllm/laguna-s-2.1-nvfp4' })).toBe(
      `"${BIN}" run "go" --auto --dir "${WS}" --model "vllm/laguna-s-2.1-nvfp4"`,
    );
  });
});
