// cronLauncher.ts — the per-cron launcher script, and the tiny `/TR` value that
// points at it.
//
// WHY A SCRIPT AND NOT A COMMAND LINE. `schtasks` refuses any `/TR` longer than
// 261 characters:
//     ERROR: Value for '/TR' option cannot be more than 261 character(s).
// A self-auditing inline command repeats the log path four times and runs to
// ~1500 characters, so it can never be registered on any realistic workspace
// path. The task therefore stores only the launcher's path, and everything else
// lives in the script — where there is no length limit at all.
//
// ---------------------------------------------------------------------------
// BATCH-FILE RULES ARE NOT COMMAND-LINE RULES. Every point below was re-derived
// by execution in this context; do not port reasoning from a `cmd /c` line.
//
// 1. `%` MUST be doubled. On a command line `%%` prints literally as `%%`; in a
//    batch file `%%` is the escape that yields one literal `%`. This is the
//    exact reverse of the inline form. Because of it, `%VAR%` in a prompt is
//    now SAFE — it reaches origami as literal text — so promptHazard no longer
//    refuses it.
// 2. Do NOT prefix the invocation with `call`. `call` performs a SECOND
//    percent-expansion pass, which undoes (1) and leaks the environment in:
//    a prompt reading `summarise %USERPROFILE% please` arrived as
//    `summarise C:\Users\dev please`. `call` is only needed when the child is
//    itself a batch file (without it the launcher transfers control and never
//    returns, losing the `[end]` record) — and resolveOrigamiBinary always
//    yields `origami.exe`, which returns normally. Correct percent handling
//    wins over a robustness case that cannot occur.
// 3. `%ERRORLEVEL%` must be followed by a SPACE before `>>`. Written closed up,
//    `exit=%ERRORLEVEL%>> "log"` expands to `exit=0>> "log"`, and `0>>` parses
//    as a redirect of handle 0 — the line silently vanishes and the audit trail
//    loses its outcome. Plain `%ERRORLEVEL%` is correct here; the command-line
//    form needed `call echo %^ERRORLEVEL%`, which does NOT apply in a script.
// 4. Quote doubling for embedded quotes still holds, and the `cmd /c`
//    first/last-quote stripping trap is GONE — there is no `cmd /c` wrapper.
// ---------------------------------------------------------------------------

import { cmdQuote, batchBareText, batchPercent, runInvocation, type RunCommandSpec } from './cronCommand';
import { buildLauncherScriptPosix } from './cronPosix';

/** schtasks' own hard limit on the `/TR` value. */
export const TR_MAX_LENGTH = 261;

/** What the backend registers as "the command". Windows: the quoted launcher
 *  path (the `/TR` value). macOS: the BARE script path — launchdBackend puts
 *  it in the plist's ProgramArguments argv, where quoting would become part of
 *  the filename. */
export function taskCommand(scriptPath: string, platform: string = process.platform): string {
  return platform === 'darwin' ? scriptPath : cmdQuote(scriptPath);
}

/**
 * Why this launcher path cannot be registered, or null if it can. A workspace
 * nested deeply enough to blow the limit must be REFUSED with a clear reason —
 * registering a truncated command would produce a task that silently does the
 * wrong thing, which is the failure this whole module exists to prevent.
 * schtasks-only: launchd's argv has no such cap, so darwin never refuses.
 */
export function trLengthError(scriptPath: string, platform: string = process.platform): string | null {
  if (platform === 'darwin') return null;
  const tr = taskCommand(scriptPath, platform);
  if (tr.length <= TR_MAX_LENGTH) return null;
  return `this workspace is nested too deeply to schedule: Windows Task Scheduler caps a task's command at ${TR_MAX_LENGTH} characters and the launcher path needs ${tr.length}. Move the workspace closer to the drive root.`;
}

/**
 * The launcher script. Four lines, chained by nothing but file order, so the
 * `[end]` record is written whatever the run's exit code — the audit trail an
 * unattended 3am run leaves behind.
 *
 * A run KILLED outright cannot write its own end line; that is why `[start]`
 * comes first, so a start with no end is the visible signature of a killed or
 * still-running job rather than silence.
 *
 * The `[cmd]` line is byte-identical to the line beneath it that actually runs
 * — same string, emitted twice — so the audit record can never drift from the
 * command it claims to describe.
 */
export function buildLauncherScript(spec: RunCommandSpec, platform: string = process.platform): string {
  if (platform === 'darwin') return buildLauncherScriptPosix(spec);
  const log = cmdQuote(spec.logPath);
  // ONE escaped string, used for both the echo and the execution.
  const line = batchPercent(runInvocation(spec));
  return [
    '@echo off',
    'rem Generated by Origami Crons. Edit the cron in the Crons view, not here —',
    'rem this file is rewritten whenever the cron is saved, and deleted with it.',
    `echo [start] ${batchBareText(spec.name)} %DATE% %TIME% >> ${log} 2>&1`,
    `echo [cmd] ${line} >> ${log}`,
    `${line} >> ${log} 2>&1`,
    // The space before >> is load-bearing — see (3).
    `echo [end] %DATE% %TIME% exit=%ERRORLEVEL% >> ${log}`,
    '',
  ].join('\r\n');
}
