// cronLauncher.ts — the per-cron launcher script, and the tiny `/TR` value that points at it.
// `schtasks` refuses any `/TR` longer than 261 characters, and a self-auditing inline command runs
// to ~1500 — so the task stores only the launcher's path, and everything else lives in the script.
// Batch-file rules are NOT command-line rules, re-derived by execution: `%` must be doubled (the
// reverse of the inline form); the invocation must not be prefixed with `call` (a second
// percent-expansion pass would leak the environment in); `%ERRORLEVEL%` needs a space before `>>`,
// or `0>>` parses as a handle redirect and the line silently vanishes.

import { cmdQuote, batchBareText, batchPercent, runInvocation, type RunCommandSpec } from './cronCommand';
import { buildLauncherScriptPosix } from './cronPosix';

/** schtasks' own hard limit on the `/TR` value. */
export const TR_MAX_LENGTH = 261;

/** What the backend registers as "the command". Windows: the quoted launcher
 *  path (the `/TR` value). macOS: the BARE script path — launchdBackend puts
 *  it in the plist's ProgramArguments argv, where quoting would become part of
 *  the filename. */
export function taskCommand(scriptPath: string, platform: string = process.platform): string {
  return platform === 'darwin' ? scriptPath : cmdQuote(scriptPath);
}

/**
 * Why this launcher path cannot be registered, or null if it can. A workspace nested deep enough to
 *  blow the 261-char limit must be refused with a clear reason, rather than silently registering a
 *  truncated command. schtasks-only — launchd's argv has no such cap.
 */
export function trLengthError(scriptPath: string, platform: string = process.platform): string | null {
  if (platform === 'darwin') return null;
  const tr = taskCommand(scriptPath, platform);
  if (tr.length <= TR_MAX_LENGTH) return null;
  return `this workspace is nested too deeply to schedule: Windows Task Scheduler caps a task's command at ${TR_MAX_LENGTH} characters and the launcher path needs ${tr.length}. Move the workspace closer to the drive root.`;
}

/**
 * The launcher script. Four lines chained by file order, so the `[end]` record is written whatever
 *  the run's exit code. `[start]` comes first, so a killed run leaves a start with no end — the
 *  visible signature of a killed or still-running job. `[cmd]` is byte-identical to the line
 *  beneath it that actually runs, so the audit record can never drift from the command it
 *  describes.
 */
export function buildLauncherScript(spec: RunCommandSpec, platform: string = process.platform): string {
  if (platform === 'darwin') return buildLauncherScriptPosix(spec);
  const log = cmdQuote(spec.logPath);
  // ONE escaped string, used for both the echo and the execution.
  const line = batchPercent(runInvocation(spec));
  return [
    '@echo off',
    'rem Generated by Origami Crons. Edit the cron in the Crons view, not here —',
    'rem this file is rewritten whenever the cron is saved, and deleted with it.',
    `echo [start] ${batchBareText(spec.name)} %DATE% %TIME% >> ${log} 2>&1`,
    `echo [cmd] ${line} >> ${log}`,
    `${line} >> ${log} 2>&1`,
    // The space before >> is load-bearing — see (3).
    `echo [end] %DATE% %TIME% exit=%ERRORLEVEL% >> ${log}`,
    '',
  ].join('\r\n');
}
