// cronPosix.ts — the macOS (launchd) counterparts of cronCommand/cronLauncher's
// Windows primitives. PURE: string in, string out, nothing spawns and nothing
// touches disk, so every artifact a Mac cron registers — the sh launcher, the
// plist, the label parse — is asserted VERBATIM in tests that run on any OS.
// The exec/fs side lives in launchdBackend.ts, behind the same injectable seam
// windowsBackend uses.
//
// The launcher mirrors cronLauncher.ts's batch script line for line — same
// [start]/[cmd]/[end] audit trail, same covenant that the [cmd] record is
// byte-identical to the line that runs. Two posix-only rules:
//   1. `rc=$?` is captured on its OWN line before the [end] echo. Inside
//      `echo "[end] $(date) exit=$?"` the $(date) substitution runs first and
//      $? would then report date's exit, not the run's.
//   2. Tokens are single-quoted (shQuote): inside single quotes the shell
//      expands NOTHING, so a prompt reading `summarise $HOME please` reaches
//      origami literally. The only escape needed is the quote itself.

import { LAUNCHD_LABEL_PREFIX, type RunCommandSpec } from './cronCommand';
import type { CronSchedule } from './cronSchedule';

/** Quote one token for sh. `'` closes the quote, emits an escaped quote, and
 *  reopens: `don't` -> `'don'\''t'`. Everything else is literal inside. */
export function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** The `origami run …` invocation, sh-quoted — cronCommand.runInvocation's
 *  posix twin, token for token. */
export function runInvocationPosix(spec: RunCommandSpec): string {
  const parts = [shQuote(spec.binary), 'run', shQuote(spec.prompt), '--auto', '--dir', shQuote(spec.workspace)];
  if (spec.agent) parts.push('--agent', shQuote(spec.agent));
  if (spec.model) parts.push('--model', shQuote(spec.model));
  return parts.join(' ');
}

/** The sh launcher script. Same shape as the batch one: [start] first so a
 *  killed run leaves a start with no end (the visible signature), the [cmd]
 *  audit line byte-identical to the line that runs, [end] whatever the exit. */
export function buildLauncherScriptPosix(spec: RunCommandSpec): string {
  const line = runInvocationPosix(spec);
  return [
    '#!/bin/sh',
    '# Generated by Origami Crons. Edit the cron in the Crons view, not here -',
    '# this file is rewritten whenever the cron is saved, and deleted with it.',
    `LOG=${shQuote(spec.logPath)}`,
    `echo ${shQuote(`[start] ${spec.name}`)}" $(date)" >> "$LOG" 2>&1`,
    `echo ${shQuote(`[cmd] ${line}`)} >> "$LOG"`,
    `${line} >> "$LOG" 2>&1`,
    'rc=$?',
    `echo "[end] $(date) exit=$rc" >> "$LOG"`,
    '',
  ].join('\n');
}

/** launchd's StartCalendarInterval counts Sunday as 0; WEEKDAYS is Mon-first. */
const LAUNCHD_WEEKDAY: Record<string, number> = { SUN: 0, MON: 1, TUE: 2, WED: 3, THU: 4, FRI: 5, SAT: 6 };

function xmlEscape(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function calendarDict(pad: string, time: string, weekday?: number): string {
  const [hh, mm] = time.split(':').map(Number);
  const day = weekday === undefined ? '' : `${pad}  <key>Weekday</key><integer>${weekday}</integer>\n`;
  return `${pad}<dict>\n${day}${pad}  <key>Hour</key><integer>${hh}</integer>\n${pad}  <key>Minute</key><integer>${mm}</integer>\n${pad}</dict>`;
}

/** The schedule keys of the plist. daily/weekly are absolute → calendar
 *  entries; hourly/minutely are intervals counted from load — the same
 *  registered-at anchor schtasks /MO uses, which is what cronSchedule.nextRun
 *  already models (lastSyncedAt). */
export function launchdScheduleXml(schedule: CronSchedule): string {
  switch (schedule.kind) {
    case 'daily':
      return `  <key>StartCalendarInterval</key>\n${calendarDict('  ', schedule.time)}`;
    case 'weekly': {
      const dicts = schedule.days.map((d) => calendarDict('    ', schedule.time, LAUNCHD_WEEKDAY[d])).join('\n');
      return `  <key>StartCalendarInterval</key>\n  <array>\n${dicts}\n  </array>`;
    }
    case 'hourly':
      return `  <key>StartInterval</key><integer>${schedule.every * 3600}</integer>`;
    case 'minutely':
      return `  <key>StartInterval</key><integer>${schedule.every * 60}</integer>`;
  }
}

/** The complete user-agent plist. ProgramArguments is an ARGV — launchd does no
 *  shell parsing, so the script path needs no quoting, only XML escaping. The
 *  launcher owns all logging, so no StandardOutPath here. */
export function plistFor(label: string, scriptPath: string, schedule: CronSchedule): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <key>Label</key><string>${xmlEscape(label)}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    '    <string>/bin/sh</string>',
    `    <string>${xmlEscape(scriptPath)}</string>`,
    '  </array>',
    launchdScheduleXml(schedule),
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

/**
 * Our labels out of `launchctl list` (three whitespace-separated columns:
 * PID, last-exit status, label). Rows for anything not carrying our prefix are
 * dropped, so a caller can never mistake somebody else's agent for a cron —
 * the exact rule parseQueriedTaskNames applies to schtasks output.
 */
export function parseLaunchctlList(stdout: string): string[] {
  const names: string[] = [];
  for (const line of stdout.split('\n')) {
    const cols = line.trim().split(/\s+/);
    const label = cols[2];
    if (label && label.startsWith(LAUNCHD_LABEL_PREFIX)) names.push(label);
  }
  return names;
}
